#!/usr/bin/env python3
import sys,os
import os.path
from optparse import OptionParser


def add_local_venv_sitepackages():
    """Add .venv site-packages to sys.path when launching with system Python."""
    base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
    venv_lib = os.path.join(base_dir, '.venv', 'lib')
    if not os.path.isdir(venv_lib):
        return
    for entry in os.listdir(venv_lib):
        if not entry.startswith('python'):
            continue
        site_packages = os.path.join(venv_lib, entry, 'site-packages')
        if os.path.isdir(site_packages) and site_packages not in sys.path:
            sys.path.insert(0, site_packages)


add_local_venv_sitepackages()

def reexec_with_pythonw():
    if sys.platform == 'darwin' and\
           not sys.executable.endswith('MacOS/Python'):
        print('re-executing using pythonw', file=sys.stderr)
        os.execvp('pythonw',['pythonw',__file__] + sys.argv[1:])

def getNeverDir(path):
    while os.path.basename(path) != 'neveredit' and\
          os.path.basename(path) != 'bin' and\
          os.path.dirname(path) != path:
        path = os.path.dirname(path)
    if os.path.basename(path) == 'bin':
        path = os.path.join(os.path.dirname(path),'lib/python')
    elif os.path.basename(path) == 'neveredit':
        path = os.path.dirname(path)
    return path

# Make local source importable when running from a checkout.
local_source_root = getNeverDir(os.path.abspath(os.path.dirname(__file__)))
if local_source_root not in sys.path:
    sys.path.insert(0, local_source_root)

parser = OptionParser()
parser.add_option('--devel',action='store_true',dest='devel',
                  help='run in development mode (does not use installed version)')
parser.add_option('--disable_pythonw',action='store_true',dest='no_pythonw',
                  help='disable automatically running pythonw on Mac')
parser.add_option('-v','--version',action='store_true',dest='version',
                  help='Display neveredit version')

options,args = parser.parse_args()
    
if not options.no_pythonw:
    reexec_with_pythonw()
    
if options.devel:
    sys.path.insert(0,getNeverDir(os.getcwd()))

try:
    if options.version:
        import neveredit
    else:
        import neveredit.ui.NeverEditMainApp
except ImportError:
    print(sys.exc_info()[1])
    print(sys.path)
    print('Faulty neveredit installation: could not import main class', file=sys.stderr)
    sys.exit(1)

if options.version:
    print('neveredit module at',neveredit.__file__)
    print('neveredit version',neveredit.__version__)
    sys.exit()
    
print('Using main class from:',neveredit.ui.NeverEditMainApp.__file__)
neveredit.ui.NeverEditMainApp.run(args)
