#!/usr/bin/env python3

import sys,os,os.path
from optparse import OptionParser

def reexec_with_local_venv_python():
    """Prefer project-local .venv interpreter when available."""
    base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
    venv_python = os.path.join(base_dir, '.venv', 'bin', 'python')
    if not os.path.exists(venv_python):
        return
    try:
        current = os.path.realpath(sys.executable)
        target = os.path.realpath(venv_python)
    except OSError:
        current = sys.executable
        target = venv_python
    if current != target:
        os.execv(venv_python,[venv_python,__file__] + sys.argv[1:])


reexec_with_local_venv_python()

def reexec_with_pythonw():
    if sys.platform == 'darwin' and\
           not sys.executable.endswith('MacOS/Python'):
        print('re-executing using pythonw', file=sys.stderr)
        os.execvp('pythonw',['pythonw',__file__] + sys.argv[1:])

def getNeverDir(path):
    while os.path.basename(path) != 'neveredit' and\
          os.path.basename(path) != 'bin' and\
          os.path.dirname(path) != path:
        path = os.path.dirname(path)
    if os.path.basename(path) == 'bin':
        path = os.path.join(os.path.dirname(path),'lib/python')
    elif os.path.basename(path) == 'neveredit':
        path = os.path.dirname(path)
    return path

parser = OptionParser()
parser.add_option('--devel',action='store_true',dest='devel',
                  help='run in development mode (does not use installed version)')
parser.add_option('--disable_pythonw',action='store_true',dest='no_pythonw',
                  help='disable automatically running pythonw on Mac')
options,args = parser.parse_args()

if not options.no_pythonw:
    reexec_with_pythonw()

if options.devel:
    sys.path.insert(0,getNeverDir(os.getcwd()))
    
try:
    import neveredit.ui.ScriptEditor
except ImportError:
    sys.path.append(getNeverDir(os.path.abspath(os.path.dirname(__file__))))
    try:
        import neveredit.ui.ScriptEditor
    except ImportError:
        print(sys.exc_info()[1])
        print(sys.path)
        print('Faulty neveredit installation: could not import main class', file=sys.stderr)
        sys.exit(1)

    print('Using main class from:',neveredit.ui.ScriptEditor.__file__)
neveredit.ui.ScriptEditor.run(args)


